### ISSUE TITLE
map and listBind and weak references

### ISSUE THREAD

**Issue by gontard** [TomasMikula/EasyBind#6]
I want to bind an `ObservableList<T>` to and `ObservableList<E>.

I wrote a mapping (`map`) from the first list to an intermediate one, then i use `listBind` between the intermediate and the target. The problem is that if i don't keep a strong reference on this intermediate list, it is garbaged and the binding is dispose.

I wrote this simple test that fails:    

    public class ListMapTest {
        @Test
        public void test() throws InterruptedException {
            ObservableList<String> source = FXCollections.observableArrayList();
            source.addAll("1", "2", "8");
    
            ObservableList<Integer> intermediate = EasyBind.map(source, Integer::parseInt);
    
            ObservableList<Integer> target = FXCollections.observableArrayList();
            EasyBind.listBind(target, intermediate);
    
            assertEquals(Arrays.asList(1, 2, 8) , target);
    
            intermediate = null;
            System.gc();
            Thread.sleep(1000);
    
            source.addAll(2, Arrays.asList("3", "5"));
            assertEquals(Arrays.asList(1, 2, 3, 5, 8), target);
    
            source.remove(1, 3);
            assertEquals(Arrays.asList(1, 5, 8), target);
        }
    }

**Comment by TomasMikula** [comment]
Unfortunately, this is the expected behavior. It is a problem that comes with weak listeners. You get the same problem with bindings from JavaFX. See also my [blog post on this](http://tomasmikula.github.io/blog/2015/02/10/the-trouble-with-weak-listeners.html). In the design of EasyBind, I chose weak listeners, because that is what JavaFX does.

In ReactFX, I implemented a different approach, where the mapped list would register a normal (strong) listener on the source list and clean it up when its own listener is removed. So I would suggest you try ReactFX, namely [LiveList.map](http://www.reactfx.org/javadoc/2.0-M4/org/reactfx/collection/LiveList.html#map-javafx.collections.ObservableList-java.util.function.Function-). There is currently no equivalent for `listBind` in ReactFX. You could still use EasyBind for that, or just use [bindContent](https://docs.oracle.com/javase/8/javafx/api/javafx/beans/binding/Bindings.html#bindContent-java.util.List-javafx.collections.ObservableList-) from JavaFX (which does not return a Subscription).
